parameters:
- name: environmentName
  type: string
- name: serviceConnection
  type: string
- name: tenantId
  type: string
- name: resourceGroupName
  type: string

jobs:
- deployment: deploy_azuresqldw
  displayName: 'Deploy to AzureSQLDW'
  pool:
    vmImage: 'windows-latest'
  variables:
    sqlProjName: ddo_azuresqldw_dw
    tenantId: ${{ parameters.tenantId }}
    resourceGroupName: ${{ parameters.resourceGroupName }}
  environment: ${{ parameters.environmentName }}
  strategy:
    runOnce:
      deploy:
        steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            scriptType: 'ps'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az login --service-principal -u $(sqlsrvrUsername) -p $(sqlsrvrPassword) --tenant $(tenantId)
              # Get the managed identity principal ID
              $serverIdentity = az sql server show --name $(sqlsrvrName) --resource-group $(resourceGroupName) --query identity.principalId --output tsv
              # Assign the Directory Readers role
              az role assignment create --assignee $serverIdentity --role "Directory Readers"
              $accessToken = az account get-access-token --resource https://database.windows.net/ --query accessToken --output tsv
              Write-Host "##vso[task.setvariable variable=accessToken]$accessToken"
        # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/sql-azure-dacpac-deployment?view=azure-devops
        - task: AzureCLI@2
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            scriptType: 'ps'
            scriptLocation: 'inlineScript'
            inlineScript: |
              $accessToken = "$(accessToken)"
      
              # Connect to the database and run the SQL commands
              $sqlConnection = New-Object System.Data.SqlClient.SqlConnection
              $sqlConnection.ConnectionString = "Server=tcp:$(sqlsrvrName).database.windows.net,1433;Database=$(sqlDwDatabaseName);"
              $sqlConnection.AccessToken = $accessToken
              $sqlConnection.Open()
      
              # Debug: Print SQL command
              $createUserCommand = "CREATE USER [$(sqlsrvrUsername)@$(tenantId)] FROM EXTERNAL PROVIDER;"
              $alterRoleCommand = "ALTER ROLE db_owner ADD MEMBER [$(sqlsrvrUsername)@$(tenantId)];"
              Write-Host "Executing SQL Command: $createUserCommand"
              Write-Host "Executing SQL Command: $alterRoleCommand"
      
              $sqlCommand = $sqlConnection.CreateCommand()
              $sqlCommand.CommandText = $createUserCommand
              $sqlCommand.ExecuteNonQuery()
      
              $sqlCommand.CommandText = $alterRoleCommand
              $sqlCommand.ExecuteNonQuery()
      
              $sqlConnection.Close()
        - task: SqlAzureDacpacDeployment@1
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            AuthenticationType: 'aadServicePrincipal'
            ServerName: 'mdwdops-sql-dev-ys900.database.windows.net'
            DatabaseName: 'mdwdops-syndp-dev-ys900'
            SqlUsername : 'ac33638b-dc2f-4761-8a04-1e953da633ab'
            SqlPassword: '$(accessToken)'
            deployType: 'DacpacTask'
            DacpacFile: '$(Pipeline.Workspace)/ciartifacts/sql_dw_dacpac/$(sqlProjName).dacpac'
            AdditionalArguments: '/Variables:ADLSLocation=abfss://datalake@$(datalakeAccountName).dfs.core.windows.net /Variables:ADLSCredentialKey=$(datalakeKey)'
          displayName: 'Azure SQL Dacpac'
