parameters:
- name: environmentName
  type: string
- name: serviceConnection
  type: string
- name: tenantId
  type: string

jobs:
- deployment: deploy_azuresqldw
  displayName: 'Deploy to AzureSQLDW'
  pool:
    vmImage: 'windows-latest'
  variables:
    sqlProjName: ddo_azuresqldw_dw
    environment: ${{ parameters.environmentName }}
    tenantId:  ${{ parameters.tenantId }}
  strategy:
    runOnce:
      deploy:
        steps:
        - task: AzureCLI@2
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            scriptType: 'ps'
            scriptLocation: 'inlineScript'
            inlineScript: |
              az login --service-principal -u $(sqlsrvrUsername) -p $(sqlsrvrPassword) --tenant $(tenantId)
              $accessToken = az account get-access-token --resource https://database.windows.net/ --query accessToken --output tsv
              Write-Host "##vso[task.setvariable variable=accessToken]$accessToken"
              Write-Host "##vso[task.setvariable variable=databaseName]$(sqlDwDatabaseName)"
        # https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/sql-azure-dacpac-deployment?view=azure-devops
        - task: SqlAzureDacpacDeployment@1
          inputs:
            azureSubscription: ${{ parameters.serviceConnection }}
            AuthenticationType: 'aadServicePrincipal'
            ServerName: $(sqlsrvrName).database.windows.net
            DatabaseName: $(sqlDwDatabaseName)
            SqlUsername : '$(sqlsrvrUsername)'
            SqlPassword: $(accessToken)
            deployType: 'DacpacTask'
            DacpacFile: '$(Pipeline.Workspace)/ciartifacts/sql_dw_dacpac/$(sqlProjName).dacpac'
            AdditionalArguments: '/Variables:ADLSLocation=abfss://datalake@$(datalakeAccountName).dfs.core.windows.net /Variables:ADLSCredentialKey=$(datalakeKey)'
          displayName: 'Azure SQL Dacpac'
